events { 
    worker_connections 1024; 
}

http {
    upstream stakeholders { server stakeholders-service:8080; }
    upstream blog { server blog-service:44307; }
    upstream tours { server tours-service:44345; }
    upstream purchase { server purchase-service:44393; }

    server {
        listen 80;


        location /stakeholders/ {
            proxy_pass http://stakeholders/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /blog/ {
            proxy_pass http://blog/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /tours/ {
            proxy_pass http://tours/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

	location /purchase/ {
            proxy_pass http://purchase/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}