// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: block_saga.proto

package block_saga

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockStatusRequest) Reset() {
	*x = BlockStatusRequest{}
	mi := &file_block_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStatusRequest) ProtoMessage() {}

func (x *BlockStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_block_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStatusRequest.ProtoReflect.Descriptor instead.
func (*BlockStatusRequest) Descriptor() ([]byte, []int) {
	return file_block_saga_proto_rawDescGZIP(), []int{0}
}

func (x *BlockStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlockStatusRequest) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type BlockStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockStatusResponse) Reset() {
	*x = BlockStatusResponse{}
	mi := &file_block_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStatusResponse) ProtoMessage() {}

func (x *BlockStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_block_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStatusResponse.ProtoReflect.Descriptor instead.
func (*BlockStatusResponse) Descriptor() ([]byte, []int) {
	return file_block_saga_proto_rawDescGZIP(), []int{1}
}

func (x *BlockStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_block_saga_proto protoreflect.FileDescriptor

const file_block_saga_proto_rawDesc = "" +
	"\n" +
	"\x10block_saga.proto\x12\x04saga\"J\n" +
	"\x12BlockStatusRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tisBlocked\x18\x02 \x01(\bR\tisBlocked\"I\n" +
	"\x13BlockStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2b\n" +
	"\x14BlockSagaGrpcService\x12J\n" +
	"\x13SyncUserBlockStatus\x12\x18.saga.BlockStatusRequest\x1a\x19.saga.BlockStatusResponseB!Z\x1ffollow/internal/grpc/block_sagab\x06proto3"

var (
	file_block_saga_proto_rawDescOnce sync.Once
	file_block_saga_proto_rawDescData []byte
)

func file_block_saga_proto_rawDescGZIP() []byte {
	file_block_saga_proto_rawDescOnce.Do(func() {
		file_block_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_saga_proto_rawDesc), len(file_block_saga_proto_rawDesc)))
	})
	return file_block_saga_proto_rawDescData
}

var file_block_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_block_saga_proto_goTypes = []any{
	(*BlockStatusRequest)(nil),  // 0: saga.BlockStatusRequest
	(*BlockStatusResponse)(nil), // 1: saga.BlockStatusResponse
}
var file_block_saga_proto_depIdxs = []int32{
	0, // 0: saga.BlockSagaGrpcService.SyncUserBlockStatus:input_type -> saga.BlockStatusRequest
	1, // 1: saga.BlockSagaGrpcService.SyncUserBlockStatus:output_type -> saga.BlockStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_saga_proto_init() }
func file_block_saga_proto_init() {
	if File_block_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_saga_proto_rawDesc), len(file_block_saga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_saga_proto_goTypes,
		DependencyIndexes: file_block_saga_proto_depIdxs,
		MessageInfos:      file_block_saga_proto_msgTypes,
	}.Build()
	File_block_saga_proto = out.File
	file_block_saga_proto_goTypes = nil
	file_block_saga_proto_depIdxs = nil
}
