// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: protos/block_saga.proto

package block_saga

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockSagaServiceClient is the client API for BlockSagaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockSagaServiceClient interface {
	SyncUserBlockStatus(ctx context.Context, in *BlockStatusRequest, opts ...grpc.CallOption) (*BlockStatusResponse, error)
}

type blockSagaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockSagaServiceClient(cc grpc.ClientConnInterface) BlockSagaServiceClient {
	return &blockSagaServiceClient{cc}
}

func (c *blockSagaServiceClient) SyncUserBlockStatus(ctx context.Context, in *BlockStatusRequest, opts ...grpc.CallOption) (*BlockStatusResponse, error) {
	out := new(BlockStatusResponse)
	err := c.cc.Invoke(ctx, "/saga.BlockSagaService/SyncUserBlockStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockSagaServiceServer is the server API for BlockSagaService service.
// All implementations should embed UnimplementedBlockSagaServiceServer
// for forward compatibility
type BlockSagaServiceServer interface {
	SyncUserBlockStatus(context.Context, *BlockStatusRequest) (*BlockStatusResponse, error)
}

// UnimplementedBlockSagaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBlockSagaServiceServer struct {
}

func (UnimplementedBlockSagaServiceServer) SyncUserBlockStatus(context.Context, *BlockStatusRequest) (*BlockStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncUserBlockStatus not implemented")
}

// UnsafeBlockSagaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockSagaServiceServer will
// result in compilation errors.
type UnsafeBlockSagaServiceServer interface {
	mustEmbedUnimplementedBlockSagaServiceServer()
}

func RegisterBlockSagaServiceServer(s grpc.ServiceRegistrar, srv BlockSagaServiceServer) {
	s.RegisterService(&BlockSagaService_ServiceDesc, srv)
}

func _BlockSagaService_SyncUserBlockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockSagaServiceServer).SyncUserBlockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.BlockSagaService/SyncUserBlockStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockSagaServiceServer).SyncUserBlockStatus(ctx, req.(*BlockStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockSagaService_ServiceDesc is the grpc.ServiceDesc for BlockSagaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockSagaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saga.BlockSagaService",
	HandlerType: (*BlockSagaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncUserBlockStatus",
			Handler:    _BlockSagaService_SyncUserBlockStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/block_saga.proto",
}
