version: "3.7"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: maindb
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway/ApiGateway 
      dockerfile: Dockerfile 
    container_name: api_gateway
    restart: on-failure
    ports:
      - "8000:8080" 
    depends_on:
      - stakeholders-service
      - blog-service
      - tours-service
      - purchase-service
      - follow-service
    environment:
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT=true
    networks:
      - app-network

  blog-service:
    build:
      context: ./backend/blog/BlogService
      dockerfile: Dockerfile
    container_name: blog_service
    restart: on-failure
    environment:
      MongoDbSettings__ConnectionString: mongodb://mongodb:27017
      MongoDbSettings__DatabaseName: BlogDb
      ASPNETCORE_URLS: http://+:44307
    depends_on:
      - mongodb
      - tours-service
      - follow-service
    networks:
      - app-network
  
  follow-service:
    build:
      context: ./backend/follow
      dockerfile: Dockerfile
    container_name: follow_service
    environment:
      PORT: 8083
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password123
    ports:
      - "8083:8083"
      - "8084:8084"
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - app-network

  tours-service:
    build:
      context: ./backend/tours/ToursService  
      dockerfile: Dockerfile
    container_name: tours_service
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maindb;Username=admin;Password=admin123
      ASPNETCORE_URLS: http://+:44345;http://+:44344
    depends_on:
      - postgres
    ports:
      - "44345:44345"
      - "44344:44344"
    volumes:
      - ./tours-data/images:/app/wwwroot/images
    networks:
      - app-network

  stakeholders-service:
    build:
      context: ./backend/stakeholders
    container_name: stakeholders_service
    restart: on-failure
    ports:
      - "8080:8080"
      - "6565:6565"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/maindb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password123
      - GRPC_SERVER_PORT=6565
    depends_on:
      postgres:
        condition: service_started
      neo4j:
        condition: service_healthy
    networks:
      - app-network

  purchase-service:
    build:
      context: ./backend/purchase/PurchaseService  
      dockerfile: Dockerfile
    container_name: purchase_service
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maindb;Username=admin;Password=admin123
    depends_on:
      - postgres
      - blog-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/stakeholders
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  pgdata:
  mongodata:
  neo4jdata:

networks:
  app-network:
    driver: bridge