version: "3.7"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: maindb
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway/ApiGateway 
      dockerfile: Dockerfile 
    container_name: api_gateway
    restart: on-failure
    ports:
      - "8000:8080" 
    depends_on:
      - stakeholders-service
      - blog-service
      - tours-service
      - purchase-service
    networks:
      - app-network

  blog-service:
    build:
      context: ./backend/blog/BlogService
      dockerfile: Dockerfile
    container_name: blog_service
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maindb;Username=admin;Password=admin123
      ASPNETCORE_URLS: http://+:44307
    depends_on:
      - postgres
      - tours-service
    networks:
      - app-network

  tours-service:
    build:
      context: ./backend/tours/ToursService  
      dockerfile: Dockerfile
    container_name: tours_service
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maindb;Username=admin;Password=admin123
      ASPNETCORE_URLS: http://+:44345
    depends_on:
      - postgres
    volumes:
      - ./tours-data/images:/app/wwwroot/images
    networks:
      - app-network

  stakeholders-service:
    build:
      context: ./backend/stakeholders
    container_name: stakeholders_service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/maindb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - app-network

  purchase-service:
    build:
      context: ./backend/purchase/PurchaseService  
      dockerfile: Dockerfile
    container_name: purchase_service
    restart: on-failure
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maindb;Username=admin;Password=admin123
      ASPNETCORE_URLS: http://+:44393
    depends_on:
      - postgres
      - blog-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/stakeholders
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge