version: "3.7"

services:
  loki:
    image: grafana/loki:main-5206e3a
    networks:
      - monitoring

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main-5206e3a-amd64
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - loki
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.5.3
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  grafana:
    name: grafana

networks:
  monitoring:
    name: monitoring