INSERT INTO role (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_GUIDE') ON CONFLICT DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_TOURIST') ON CONFLICT DO NOTHING;